Repository heroku/libcnb.rs, pull requests merged in 2021-12, with the labels that each got.

#218 Extend test_layer_env_delta_fs_read_write for LayerEnv
  libcnb/src/layer_env.rs
Labels: skip changelog

#213 Update status of `clippy::missing_errors_doc`
  libcnb-data/src/lib.rs
  libcnb/src/lib.rs
Labels: skip changelog

#219 Adjust .gitignore now Cargo workspaces are being used
  .gitignore
Labels: skip changelog

#220 Remove `test_` prefix from test names
  libcnb-data/src/newtypes.rs
  libcnb/src/env.rs
  libcnb/src/layer_env.rs
Labels: skip changelog

#221 Spelling fixes
  CHANGELOG.md
  libcnb/src/layer_env.rs
  libcnb/src/platform.rs
Labels: skip changelog

#222 Tests for `Layer` and `BuildContext::handle_layer`
  libcnb/Cargo.toml
  libcnb/src/layer/handling.rs
  libcnb/src/layer/mod.rs
  libcnb/src/layer/test.rs
Labels: skip changelog

#225 Remove "authors" field from Cargo metadata
  examples/example-01-basics/Cargo.toml
  examples/example-02-ruby-sample/Cargo.toml
  libcnb-data/Cargo.toml
  libcnb/Cargo.toml
Labels: skip changelog

#216 Specify interface in readme docs
  README.md
Labels: skip changelog

#226 Remove layer types from hand-written layer metadata in layer::test
  libcnb/src/layer/test.rs
Labels: skip changelog

#227 Add missing Cargo metadata to libcnb-proc-macros
  libcnb-proc-macros/Cargo.toml
Labels: skip changelog

#231 Bump version to 0.4.0
  libcnb/Cargo.toml
Labels: skip changelog

#233 Cleanup crate dependencies
  libcnb-cargo/Cargo.toml
  libcnb-data/Cargo.toml
  libcnb-proc-macros/Cargo.toml
  libcnb/Cargo.toml
Labels: skip changelog

#236 Correct the data model for `LayerContentMetadata`
  CHANGELOG.md
  libcnb-data/src/layer_content_metadata.rs
  libcnb/src/layer/handling.rs
  libcnb/src/layer/test.rs
Labels: libcnb-data

#237 Link to PRs from changelog entries
  CHANGELOG.md
Labels: documentation

#240 Change the 01-basics example to be compatible with any stack
  examples/example-01-basics/buildpack.toml
Labels: skip changelog

#241 Fix the data model and validation of `Buildpack.version`
  CHANGELOG.md
  libcnb-data/Cargo.toml
  libcnb-data/src/buildpack/mod.rs
  libcnb-data/src/buildpack/version.rs
  libcnb/src/layer/test.rs
Labels: bug, libcnb-data
