Repository heroku/libcnb.rs, pull requests merged in 2023-10, with the labels that each got.

#696 Fix lint errors in Rust 1.73 and 1.74
  libcnb-data/src/layer_content_metadata.rs
  libcnb-package/src/cross_compile.rs
  libcnb-test/src/test_runner.rs
  libcnb/src/buildpack.rs
  libcnb/src/layer/handling.rs
  libcnb/src/layer/public_interface.rs
Labels: skip changelog

#695 Add `GH_TOKEN` env to `gh` CLI invocation
  .github/workflows/release.yml
Labels: skip changelog

#698 Improve the UX of README command codeblocks
  README.md
  libcnb-cargo/README.md
Labels: documentation, skip changelog

#703 Fix typos in comments and variable names
  libcnb-data/src/launch.rs
  libcnb-package/src/util.rs
  libcnb-test/src/test_runner.rs
Labels: skip changelog, libcnb-data, libcnb-test, libcnb-package

#707 Fix libcnb-tests's integration tests with newer Rosetta/Docker Desktop
  libcnb-test/tests/integration_test.rs
Labels: skip changelog, libcnb-test
